// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqafVQJ1qDTxIqT90rKTsdEmYkXUjG8Cc',
    appId: '1:690979149309:web:8edfae7692bc4b46b4b594',
    messagingSenderId: '690979149309',
    projectId: 'doanltdd-51e24',
    authDomain: 'doanltdd-51e24.firebaseapp.com',
    storageBucket: 'doanltdd-51e24.firebasestorage.app',
    measurementId: 'G-HY285CEZYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByzwMXppV-wC-lJw52GYF4lRIY8fe-5S0',
    appId: '1:690979149309:android:772021328bd6d8e4b4b594',
    messagingSenderId: '690979149309',
    projectId: 'doanltdd-51e24',
    storageBucket: 'doanltdd-51e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoob3eMKz6qgRdT8sHudbG0U_6Eq5sjw8',
    appId: '1:690979149309:ios:6e3fcdd0be00c4f5b4b594',
    messagingSenderId: '690979149309',
    projectId: 'doanltdd-51e24',
    storageBucket: 'doanltdd-51e24.firebasestorage.app',
    iosBundleId: 'com.example.appDoAnNhanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoob3eMKz6qgRdT8sHudbG0U_6Eq5sjw8',
    appId: '1:690979149309:ios:6e3fcdd0be00c4f5b4b594',
    messagingSenderId: '690979149309',
    projectId: 'doanltdd-51e24',
    storageBucket: 'doanltdd-51e24.firebasestorage.app',
    iosBundleId: 'com.example.appDoAnNhanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqafVQJ1qDTxIqT90rKTsdEmYkXUjG8Cc',
    appId: '1:690979149309:web:6331361e7db14418b4b594',
    messagingSenderId: '690979149309',
    projectId: 'doanltdd-51e24',
    authDomain: 'doanltdd-51e24.firebaseapp.com',
    storageBucket: 'doanltdd-51e24.firebasestorage.app',
    measurementId: 'G-VK4JMPZ2BB',
  );
}
